import type { Meta, StoryObj } from '@storybook/react';
import { CodeBlock } from '../../components/sections/code-block';

const meta: Meta<typeof CodeBlock> = {
  title: 'Sections/CodeBlock',
  component: CodeBlock,
  parameters: { layout: 'fullscreen' },
};
export default meta;

type Story = StoryObj<typeof CodeBlock>;

const sampleCode = `import { PolaGate } from '@polastack/gate';

// スキーマからSDKを自動生成
const client = PolaGate.createClient({
  tenant: 'my-saas',
  apiKey: process.env.POLASTACK_API_KEY,
});

// 型安全なAPI呼び出し
const users = await client.users.list({
  filter: { role: 'admin' },
  search: 'tanaka',
});`;

export const Centered: Story = {
  render: (_, { globals }) => {
    const isJa = globals.locale === 'ja';
    return (
      <CodeBlock
        eyebrow={isJa ? 'コード例' : 'CODE EXAMPLE'}
        title={isJa ? '10分で統合完了' : 'Integrate in 10 minutes'}
        subtitle={
          isJa
            ? 'PolaGateが生成する型安全なSDKで、すぐに開発を始められます。'
            : 'Start developing immediately with type-safe SDKs generated by PolaGate.'
        }
        code={sampleCode}
        language="typescript"
        filename="app/api/users.ts"
      />
    );
  },
};

export const SplitLayout: Story = {
  render: (_, { globals }) => {
    const isJa = globals.locale === 'ja';
    return (
      <CodeBlock
        layout="split"
        title={isJa ? '型安全なAPI呼び出し' : 'Type-safe API calls'}
        subtitle={
          isJa
            ? 'スキーマ定義からTypeScript SDKを自動生成。手動でのAPI実装は不要です。'
            : 'Auto-generate TypeScript SDK from schema definitions. No manual API implementation needed.'
        }
        code={sampleCode}
        language="typescript"
        filename="app/api/users.ts"
        background="dark"
      />
    );
  },
};

export const SplitLayoutTopAligned: Story = {
  render: (_, { globals }) => {
    const isJa = globals.locale === 'ja';
    return (
      <CodeBlock
        layout="split"
        alignment="top"
        title={isJa ? '型安全なAPI呼び出し' : 'Type-safe API calls'}
        subtitle={
          isJa
            ? 'スキーマ定義からTypeScript SDKを自動生成。手動でのAPI実装は不要です。'
            : 'Auto-generate TypeScript SDK from schema definitions. No manual API implementation needed.'
        }
        code={sampleCode}
        language="typescript"
        filename="app/api/users.ts"
        showLineNumbers
      />
    );
  },
};
